# Generated by Django 5.1.1 on 2025-03-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, default='icon.jpg', null=True, upload_to='contacts_photo/'),
        ),
    ]
